### ISSUE TITLE
bool dialog cannot go back for small-size screen

### ISSUE THREAD

**Issue by iron9light** [jtsage/jquery-mobile-simpledialog#1]
It's cannot go back when I click button. on my Android portrait mode and my desktop chrome when it's small.

```
    $(this).simpledialog({
        'mode' : 'bool',
        'prompt' : name,
        'buttons' : {
            'Add': function () {
                $(document).trigger('addtask', name);
            },
            'Cancel': function () {
            }
        }
    })
```

**Comment by jtsage** [comment]
Yes, I actually had noticed this too - It's actually a limitation on how jQM works - I will look into a solution, but right now I am pretty much waiting to see which direction jQM goes with this first.  Fwiw, you can force this plugin to not use the builtin dialogs, which will sort of fix the problem (well, it's a workaround anyway).  Add useDialogForceFalse: true to your options.

**Comment by jtsage** [comment]
Please test this functionality again - I made some progress with this problem on DateBox, thanks to a contributor, I believe it should work as expected now.
