### ISSUE TITLE
Variable Window Size for open html

### ISSUE THREAD

**Issue by dannyc** [jtsage/jquery-mobile-simpledialog#11]
Would be nice if there was an option for variable window size for free open html mode.  Currently there is a limited width.  Common use case would be in scenarios where user would like to use a full page div, but not have it fill full width and height.  When I shove a lot of html content in there, the whole layout breaks.

**Comment by jtsage** [comment]
Hmm, I will look at this - however, you may be better off just modifying the css for your use.  Without looking to hard, I believe you need to change the width of:

```
.ui-simpledialog-container 
```

That _should_ be it.
