### ISSUE TITLE
Add a option to run a function when call simpledialog('close') when use raw html mode

### ISSUE THREAD

**Issue by vssantoss** [jtsage/jquery-mobile-simpledialog#17]
If I can do something like it

```
$('#dialoglink').live('click', function() {
    $(this).simpledialog({
        'mode' : 'blank',
        'prompt': false,
        'forceInput': false,
        'useModal':true,
        'closeFunction':function() {
            // Do something here
        },
        'fullHTML' : 
            "<ul data-role='listview'><li>Some</li><li>List</li><li>Items</li></ul><a data-role='button' href='#' id='simpleclose'>Close</a>"
    })
});
$('#simpleclose').live('click', function() {
    $('#dialoglink').simpledialog('close');
});
```

When I click Close, the function I passed to 'closeFunction' parameter will run after dialog close.

Thank you for your great work.

**Comment by asgeo1** [comment]
Why not just put that logic in the #simpleclose click handler, after the call to simpledialog('close') ?

If anything, it would be more useful if the simpledialog triggered events like 'open', 'close' etc, and then you could bind to those events if you wanted. I.e. that is what jQueryUI dialog does.

**Comment by jtsage** [comment]
I did add the same sort of event scheme as datebox has - open and close both throw 'SimpleDialog' with a payload.  Check out the demos site for more info.
