### ISSUE TITLE
Do not close raw html dialog when click out dialog

### ISSUE THREAD

**Issue by vssantoss** [jtsage/jquery-mobile-simpledialog#18]
If I use raw html dialog, when I click out it, dialog closes.

I changed lines 257-259 from

```
            if ( !o.forceInput ) {
                self.close();
            }
```

to

```
            if ( !o.forceInput ) {
                if ( o.mode !== 'blank' ) self.close();
            }
```

and now it's ok to me.

Thank you.

**Comment by jtsage** [comment]
This is actually exactly what the forceInput configuration option was intended for.
