### ISSUE TITLE
useModal doesn't seem to work

### ISSUE THREAD

**Issue by renaissanceGeek** [jtsage/jquery-mobile-simpledialog#20]
First of all, thanks for this plug-in--I was getting frustrated with jqm's lack of support for this and having trouble creating my own.  But I really need a modal dialog, and this doesn't seem to do it. The background isn't faded out, and everything in the background is still clickable.  In fact, you can even click the link that opened the dialog in the first place, which opens another dialog on top of the first.

Maybe I'm doing something wrong, but I'm not sure what.  Here's how I call the plug-in:

```
                $(el).simpledialog({
                    'mode': 'bool',
                    'prompt': "This action can be performed only in the full desktop version.",
                    'useDialogForceFalse': true,
                    'useModal': true,
                    'forceInput':true,
                    'buttons': {
                        'Go to full site': {
                            click: function ()
                            {
                                var url = orgUrl;
                                gaOptValue = gMobileUtils.extractAction(url);
                                qb.ga.AddEvent("Unsupported", "Action", gaOptValue, 1);
                                location.assign(url);
                            },
                            theme: "s",
                            icon: false
                        },
                        'Stay on this page': {
                            click: function ()
                            {
                                var url = orgUrl;
                                gaOptValue = gMobileUtils.extractAction(url);
                                qb.ga.AddEvent("Unsupported", "Action", gaOptValue, 0);
                            },
                            theme: "c",
                            icon: false
                        }
                    }
                });
```

**Comment by jtsage** [comment]
Browser / Device combo?  It seems to work just fine on chrome here - (example) http://dev.jtsage.com/jQM-SimpleDialog/demos/bool.html

**Comment by vssantoss** [comment]
What is the el?

In the latest version of jqm simpledialog I noticed that the object that receives the jqm simpledialog must be inside the data-role page of the jqm. Check this.

```
<div data-role="page">
    <div data-role="header">
        <h1>Header</h1>
    </div>

    <div data-role="content">
        <p id="ptmp">Content</p>
    </div>
    <div id="divtmp"></div>
</div>

// This works because ptmp is inside page div
$("#ptmp").simpledialog({
    ...
});

// This doesn't because divtmp is outside page
$("#divtmp").simpledialog({
    ...
});
```

**Comment by renaissanceGeek** [comment]
vehuel--thanks, that was indeed the problem!

**Comment by Axeia** [comment]
I can still click 'through' the dialog Window on a HTC Hero with Android 2.1 and the default browser. It's a bit random, sometimes the elements in the Window get the focus/are 'clicked'. Sometimes the click seems to go straight to window and selects one of the <input> or <select> elements behind it.
