### ISSUE TITLE
simpledialog don't refresh position when use refresh method

### ISSUE THREAD

**Issue by vssantoss** [jtsage/jquery-mobile-simpledialog#24]
I think this is a new issue, which did not exist before.

If you update the contents of the window and call the refresh method to update the content, the window size changes but it remains the same distance from the left side without being centralized.

**Comment by jtsage** [comment]
hmm.  indeed it would if it was already open.  Um, lemme see what I can do on this to make it not horrendously hacky.  I assume you are seeing this problem in popup mode?

**Comment by vssantoss** [comment]
Yes. This problem occurs in popup mode.

Thank you.

**Comment by jtsage** [comment]
alrighty, added a trap for the popup being open and refreshed.  Seems to work.
