### ISSUE TITLE
useDialogForceFalse: true not working on RC2?

### ISSUE THREAD

**Issue by vicsanca** [jtsage/jquery-mobile-simpledialog#25]
With useDialogForceFalse: false open fine and with true don't show dialog. With simpledialog RC1 was working fine.
Tested on android 2.3.5

**Comment by vicsanca** [comment]
Great work with this plugin :). Congratulations and thanks.

**Comment by vicsanca** [comment]
OK, looks like 'useModal': true is needed to make useDialogForceFalse: false works.

Is possible to use forceInput' : false with useModal: true y useDialogForceFalse: false? not working here.

Thanks again.

**Comment by jtsage** [comment]
hmm - I'm not totally sure I follow.

1.) useDialogForceFalse = false doesn't really do anything. (if true, force the dialog [page] mode, if false, basically ignore).

At any rate, tried your combined options forceInput: false, useModal: true, useDialogForceFalse: both options without any issue.  

BUT.  

I did just fix a huge bug in the dialog[page] mode, maybe this caught it?  (Also, there was a bug in the forceInput: false code now that I think about it....  )

Anyway, can you test again and see if I accidentally fixed this?

**Comment by vicsanca** [comment]
Yes, forceInput: false now works with useModal: true :)
Thanks. You are fast.
