### ISSUE TITLE
Non-native select menu does not trigger from inside Full Html Dialog

### ISSUE THREAD

**Issue by stumaca** [jtsage/jquery-mobile-simpledialog#29]
First of all great work on this widget and the Datebox but I have an issue when adding jquery mobiles non-native (data-native-menu='false') select box to a Simple Dialog FullHtml example the selects popup area does not display. Works when using the native menu though.

See preview.flipmind.com/pos/test.html for an example of the Non-native select not working.

**Comment by jtsage** [comment]
Alright - 2 options:

1.) the easy workaround:  useDialogForceTrue - if simpledialog opens a new page, the select menu will work as expected.

2.) What I just commited to fix it for popup mode.  Note, when using this, I _highly_ recommend using it with the option 'closeOnClose' set to true - the hackish way to do this kind of leaves a mess in the DOM, and if your screen size changes to auto-flip to dialog mode, it won't open there.

**Comment by jtsage** [comment]
Example: http://jsfiddle.net/jtsage/RQ5r2/5/
