### ISSUE TITLE
Ability to make 'prompt' optional

### ISSUE THREAD

**Issue by kevinlieb** [jtsage/jquery-mobile-simpledialog#3]
I would like to have the 'prompt' window title at the top be optional.  I have done this code locally but perhaps a bit sloppily.  So I am putting in a request to the creator...

**Comment by jtsage** [comment]
Added this functionality, simply set the prompt to "false" and it will not show up.  Example at http://dev.jtsage.com/jQM-SimpleDialog/ also updated.  Sorry for the delay, real life and all that. ( SHA: 90eb2011be287df965cdd2555962c8890e0cd56b )
