### ISSUE TITLE
dialog opens under navbar

### ISSUE THREAD

**Issue by barbalex** [jtsage/jquery-mobile-simpledialog#32]
Hi

Thanks for this very nice tool.

It works great for me but for this issue. You can see it on my site (in development):
http://barbalex.iriscouch.com/evab/_design/evab/index.html   log in with "Name" = "z" and "Passwort" = "z"
Then use this link: http://barbalex.iriscouch.com/evab/_design/evab/_show/hZeitEdit/6c37f527c1c7e9b93440cd2795003701
and click the simpledialog icon on the topmost field. See how it lies under the navbar. This is worse on this page here, when it is viewed in a small window and opening the simpledialog for the lowermost field: http://barbalex.iriscouch.com/evab/_design/evab/_show/BeobEdit/69fa295c7e71d522c656e67404c906bc
because it is not possible to click the hidden set time button.

Am I doing something wrong?

Happy new year!

Alex

**Comment by jtsage** [comment]
Been playing a bit with your app - looks very nice (no idea what it does, as I don't speak the language - but it's pretty!!)

My guess is this has something to do with using fixed headers/footers.  I'll play and see what I can do to fix this - last time I worked a lot on this project, those still didn't work, so I didn't spend much time on it. :)

**Comment by barbalex** [comment]
the app is to register sightings of species (plants, animals, mosses,
funghi). It has views for hobbyists and for proffessionals. the later can
configure freely what information they register and what fields they see.
The sightings can be provided to Swiss nature conservancy agencies. The app
is in development. Should get on iOS and Android, a website and installable
on windows and mac

Thanks for looking. It is a very nice and useful tool

Alex

Am Samstag, 7. Januar 2012 schrieb J.T. Sage <
reply@reply.github.com

> :
> Been playing a bit with your app - looks very nice (no idea what it does,
> as I don't speak the language - but it's pretty!!)
> 
> My guess is this has something to do with using fixed headers/footers.
>  I'll play and see what I can do to fix this - last time I worked a lot on
> this project, those still didn't work, so I didn't spend much time on it. :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/jtsage/jquery-mobile-simpledialog/issues/32#issuecomment-3393721

## 

---

Alexander Gabriel
Wiesenstrasse 22
8800 Thalwil
079/ 372 51 64
alex@barbalex.ch
www.barbalex.ch

**Comment by DuStorm** [comment]
I've goten this to work, have to tweak the alignment by just using an arbitrarily larger z-index (10000) in the script.
