### ISSUE TITLE
simpledialog always displays at the top of the page on iOS5

### ISSUE THREAD

**Issue by sirlantzalot** [jtsage/jquery-mobile-simpledialog#35]
First off thanks for a great dialog solution! 

I have a list, scroll down the list and press a "add" button and dialog displays perfectly under Chrome(OSX10.7.2) but when I open the same page on my iOS5 phone the dialog is always displayed at the top of the page even though I have scrolled midway through the list. 

Any settings I could be missing here?

```
  $($.mobile.activePage).simpledialog({  
    'mode' : 'string',
    'cleanOnClose' : true,
    'prompt' : 'Quantity',
    'transition' : 'pop',
    'useDialogForceFalse' :true,
    'useModal': true,
    'buttons' : { 
```

Thanks!

Steve...

**Comment by rbdcti** [comment]
I am also seeing this kind of behavior on iOS 5 (displayed near the top). Also, the page gradient is cut off under the dialog (I opened a separate issue for this). Screenshot of this here: http://dl.dropbox.com/u/9719672/misc/jqmsimpledialog-ios5.png

**Comment by jtsage** [comment]
Steve - its actually working as designed - your attaching to the page. But you're right, I would expect the dialog (pop up) to respect the scroll position. I'll see what I can do

**Comment by sirlantzalot** [comment]
Thanks, yes, if I attach it to something within the list it still shows at the top of the page.

**Comment by sirlantzalot** [comment]
just to close the issue this is now working in SimpleDialog2, cool!
