### ISSUE TITLE
Page gradient cut off on iOS5 (at least)

### ISSUE THREAD

**Issue by rbdcti** [jtsage/jquery-mobile-simpledialog#38]
Using a simple logout-like dialog:
```$(document).delegate('.hdrLogoutBtn', 'click', function() {
$(this).simpledialog({
  'mode' : 'bool',
  'prompt' : 'Logout?',
  'cleanOnClose': true,
  'useModal': true,
  'buttons' : {
    'Yes': {
      click: function () {
    $.get("/logout", function(data) {
      location.reload(true); //do not use cache: request from the server
    });
      }
    },
    'No': {
      click: function () {
      },
      icon: "delete",
      theme: "c"
    }
  }
});
});

```

The page gradient is being cut off in iOS 5. Screenshot of this here on an iPhone4 running iOS 5.x: http://dl.dropbox.com/u/9719672/misc/jqmsimpledialog-ios5.png

(Sorry about the formatting of the code above, for some reason the tabs/spaces I paste in aren't showing...)
```

**Comment by rbdcti** [comment]
Just tried on Opera mobile, this same code looks fine (page gradient continues, etc)

**Comment by jtsage** [comment]
Interesting.  This is something with the underlying dialog method (I think), I'll see if I can figure an easy workaround.
