### ISSUE TITLE
modal simpledialog doesn't shade out fixed header and footer

### ISSUE THREAD

**Issue by rbdcti** [jtsage/jquery-mobile-simpledialog#42]
See http://dl.dropbox.com/u/9719672/misc/simpledialog-zindexbug.png

I fixed this by overriding a few styles in my code:

.ui-simpledialog-container {
  z-index: 10001 !important;
}
.ui-simpledialog-screen-modal {
  z-index: 10000 !important;
}

(basically the zindex needs to be higher than what jquery mobile uses for the fixed header and footer, which is 1000 at least with jqm1.1)

**Comment by jtsage** [comment]
fwiw, there is also a zindex option in simpledialog - in this case, you'd set it to 10001 to generate the same thing (it sets the zindex of the container, and the modal overlay as -1 from whatever is specified)

**Comment by rbdcti** [comment]
Ahh, good to know. You may want to default it to 1005 or something like that to fix this issue.

**Comment by rbdcti** [comment]
Also your simpledialog2 docs have a minor error: The docs say "zIndex" for the option name, while the code uses "zindex"

**Comment by jtsage** [comment]
Fixed the doc issue - still considering the zindex default.  The issue is, if I change it, datebox inside of simpledialog2 won't work anymore - nor will any expected behavior on existing installs if folks are counting on the current default.

**Comment by rbdcti** [comment]
Ok makes sense. I'm using zindex in my code and will close this one out. Thanks for the assistance!
