### ISSUE TITLE
Trying to remove icons while in Bool mode

### ISSUE THREAD

**Issue by Prufrock1** [jtsage/jquery-mobile-simpledialog#43]
Hi, great plugin, just wanted to know if there was a good way to remove the button icons in bool mode. Thus far, I haven't been able to remove them.
I've found its possible in raw mode by creating an element w/o data-icon attribute but I'm trying to stick with the boolean functionality. Thanks!

**Comment by jtsage** [comment]
Yes, pass the icon as FALSE - no quotes, it must be the boolean.

i.e. 

'ok': {
  'icon': false,
  'click': ...etc...
}
