### ISSUE TITLE
Modal background partially overlaps dialog

### ISSUE THREAD

**Issue by rbdcti** [jtsage/jquery-mobile-simpledialog#45]
This is with the newest simpledialog2 version from master (02/27). I have a dialog like the following that I create in a function call (e.g. not an event handler as a response to a click event or whatever):

``` javascript
        $(document).simpledialog2({
          'mode' : 'button',
          'zindex': 10005,
          //'showModal': false,
          'buttonPrompt' : 'End chat?',
          'buttons' : {
            'Yes': {
              click: function () {
                endChat(true);
              },
              icon: "check",
            },
            'No': {
              click: function () {
              },
              icon: "back",
              theme: "c"
            }
          }
        });
```

On both the iPhone and Firefox desktop, the dialog ends up looking like: http://dl.dropbox.com/u/9719672/misc/simpledialog2.png

If I set showModal to false, it appears as it should. Also, taking off that zindex value doesn't do anything differently. T(I am using fixed toolbars too.)

**Comment by rbdcti** [comment]
I tried tweaking the css also in firebug a bit but wasn't able to make any progress unless I just disabled the modal background div (display: none)

**Comment by rbdcti** [comment]
Note that I'm using JQM 1.1rc1 so the problem may be all the themeroller/jqm hanky panky going on as it nears 1.1 ...let me see if I can try with an older theme (I think some of the changes to themeroller over the past few days broke the themes)

**Comment by rbdcti** [comment]
This was an issue with themeroller theme imports. Closing.

**Comment by jtsage** [comment]
Cool cool.  As it happens, there were a few weeks when the 'a' theme always did that, then it went away - my assumption then was something had changed/corrected upstream
