### ISSUE TITLE
Dialog shows always the same message

### ISSUE THREAD

**Issue by vssantoss** [jtsage/jquery-mobile-simpledialog#5]
I created the page below to display the error.

http://www.wapps.com.br/test/simpledialog-error.htm

If I click on the count++ three times the dialog prompt shows always count = 0.

So if I click on count-- the first dialog displays count = 3 then the dialog prompt is always in "count = 3" independent if the value of count change.

You can check the value of count by clicking Show Count.

How can I solve this?

Thank you, this is a very useful plugin.

**Comment by jtsage** [comment]
Indeed - and actually, you are doing it exactly right - the problem is, the plugin never re initializes the title (I didn't see any reason I'd need to) - You proved me otherwise.  This behavior has been corrected below - using your example, I believe it works as expected now.
