### ISSUE TITLE
Simpledialog 2 does not seem to work with JQM 1.1 RC1 with a custom theme

### ISSUE THREAD

**Issue by MongooseSec** [jtsage/jquery-mobile-simpledialog#50]
I cannot seem to get simpledialog2 to work with JQM 1.1RC1 and jquery 1.7.2 with a custom theme, even though the original works just fine. The dialog simply never pops up.

**Comment by raldred** [comment]
I've been using the sd2 with a custom theme on rc1 fine, now on rc2 and still working fine.

**Comment by caractereschinois** [comment]
I have issues too. There seems to be many side effects within simpledialog2.
You can find it illustrated there: http://jsfiddle.net/nsdrL/
Thanks for your help!

**Comment by caractereschinois** [comment]
Sorry, I am going to post this in an separate post because it does not really belong to this one.
