### ISSUE TITLE
simpledialog2 frequency limit

### ISSUE THREAD

**Issue by ray007** [jtsage/jquery-mobile-simpledialog#55]
I had been wondering why only the first dialog in my info-queue was visible.
After some debugging I found, that the second once was visible for a short time as well but got destroyed by by the destroy-timeout from the first dialogs close.

How about changing

setTimeout("$.mobile.sdCurrentDialog.destroy();", 1000);

into

setTimeout(function() { self.destroy(); }, 1000);

?
Not a perfect solution, but better than now I think ...

**Comment by avidenie** [comment]
I'm opening a new dialog when clicking on one of the buttons of the main dialog and I have the same issue. My first idea was to open the second dialog on callbackClose, but unfortunately that is called before the dialog is actually closed.

Any idea on how to open a second dialog from the main dialog, after the main dialog closes?

**Comment by ray007** [comment]
Either add "animate: false" to the dialog config (which is what I did for now) or delay the opening of the second dialog for more than 1 second;
That or patching simpledialog2.js as I hinted above I guess ...

Another option would probably be to reuse the dialog instead of closing it and opening a new one, haven't had much time to experiment with the possibilities ...

**Comment by jtsage** [comment]
Mmm, the delay is annoying.  I _think_ I've got it licked - pretty much, I didn't fully understand how to make setTimeout play well with others - change hitting on next commit.
