### ISSUE TITLE
Reset the style of the buttons on a window re-display

### ISSUE THREAD

**Issue by vssantoss** [jtsage/jquery-mobile-simpledialog#6]
Sorry to bother you again and thank you for implementing the solution to my last problem.

Would it be possible on a window re-display, reset the style of the buttons?

Using the same example page (http://www.wapps.com.br/test/simpledialog-error.htm) if I click on count++ button and click the Yes the window closes. However if I click the button count++ again, the Yes button now appears as if it were clicked.

I use your plugin in a mobile application with a function similar to the VB MsgBox. So I had trouble with the window title and now this detail that is not really a problem for me. I hate jQ Mobile dialog.

Thank you very much again.

**Comment by jtsage** [comment]
Yeah, I see the issue - the problem with jQM is, if you play with the "normal" flow of events, those extra classes don't get cleared.  Now .ui-btn-active is dumped from all buttons on open, should fix the issue.
